config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  get 'messages/new'
  devise_for :users
  root to: "main#index"
  resources :main, only: [:index, :new]
  resources :users, only: [:edit, :update]
  resources :messages, only: [:create]
  resources :blogs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    
    validates :title, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
    validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blog
  has_many :message

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }

  with_options presence: true do
    validates :name
    validates :email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    
    private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog, only: [:edit, :show, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
  end

  def create
    Blog.create(blog_parameter)
    redirect_to blogs_path
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
  end

  def update
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render edit
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
  end

  def new
    @cdate = Date.today
  end

  private

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @messages = Message.all
    @message = Message.new
    @name = current_user.name
  end

  def create
    @message = Message.new(text: params[:message][:text])
    if @message.save
      ActionCable.server.broadcast 'message_channel', content: @message
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def edit
    end

    def update
        if current_user.update(user_params)
            redirect_to root_path
        else
            render :edit
        end
    end

    
    private
    
    def user_params
       params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>貯金記録</h1>

<table>
  <thead>
    <tr>
      <th>貯金金額</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to '詳細', blog %></td>
        <td><%= link_to '編集', edit_blog_path(blog.id) %></td>
        <td><%= link_to '削除',blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to(new_blog_path, class:'omikuji-btn') do %>
  <button class='omikuji-btn-text'>貯金記録を入力する！</button>
<% end %>

<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chokinomikuji</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">貯金おみくじ</a></h1>
        <% if user_signed_in? %>
            <div class="user_nav grid-6">
              <span><%= current_user.name %>
                 <ul class="user__info">
                   <li>
                     <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
                   </li>
                 </ul>
               </span>       
            </div> 
        <% else %> 
            <div class="grid-6">    
              <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
              <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
            </div>
        <% end %>  
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright ChokinOmikuji 2021.
      </p>
    </footer>
  </body>
</html>

app/views/main/index.html.erb
<div class='main'>
 <div class='title-contents'>
    <h2 class='service-title'>
      毎日の楽しみが増える貯金おみくじアプリ
    </h2>
    <p class='service-explain'>
      貯金記録を残そう！！
    </p>
    <p class='service-explain'>
      貯まったお金で旅行しよう！
    </p>
 </div>

 <div class='second-contents'>
      <%= image_tag "buta_san.png", class:"list-pict" %>
 </div>
 <%= link_to(new_main_path, class: 'omikuji-btn') do %>
  <button class='omikuji-btn-text'>おみくじを引いてみる</button>
 <% end %> 
 <%= link_to(blogs_path, class: 'chokinomikuji-btn') do %>
 <button class='chokijiomikuji-btn', id="kekka_btn">貯金記録</button>  
 <%end%>
 <%= link_to(messages_new_path, class: 'chokinomikuji-btn') do %>
 <button class='chokijiomikuji-btn', id="kekka_btn">なんでもメモ</button>  
 <%end%>
</div>

app/views/main/new.html.erb
<div class='second-contents'>
    <%= image_tag "buta_san.png", class:"list-pict" %>
</div>
<button class='chokinomikuji-btn', id="btn">おみくじスタート</button>  
  <%= link_to(blogs_path, class: 'chokinomikuji-btn') do %>
     <button class='chokijiomikuji-btn'>貯金記録入力</button>
  <%end%>
<div id="disp"></div>  

<div class='omikuji-contents'>
<div id="disp"></div> 
 <script>
     var omikuji_items = [ "1000円！！！", "500円！！！", "100円！！！", "50円！！！", "10円！！！", "5円！！！"];
     var btn =document.getElementById("btn");
     var disp = document.getElementById("disp");
     var num = 0;

     btn.addEventListener("click",function(){
         var num = Math.floor(Math.random() * omikuji_items.length);
         var result = omikuji_items[num];
         disp.innerHTML = result;

         if(result == "1000円！！！"){
             alert("今日はめっちゃ良い日やな〜");
         }else if(result == "500円！！！"){
             alert("ちょうどええ金額やな〜")
         }else {
             alert("今日は控えめやな〜")
         }
     })
 </script>
 <%= @cdate %>
</div> 

app/views/messages/new.html.erb
<div class="contents row">
  <p><%= @name %>さんの結果一覧</p>
</div>

<h3>なんでもメモ</h3>
<%= form_with model: @message do |f| %>
  <%= f.text_field :text %>
  <%= f.submit '送信' %>
<% end %>
<div id='messages'>
  <% @messages.reverse_each do |message| %>
    <p><%= message.text %></p>
  <% end %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>